//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSLERP.DataManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Company
    {

        public int c_ID { get; set; }
        public int c_g_ID { get; set; }
        public String c_Name { get; set; }
        public String c_Address { get; set; }
        public String c_FactoryAddress { get; set; }
        public String c_Remarks { get; set; }
        public String c_ContactNo { get; set; }
        public String c_Email { get; set; }
        public String c_Web { get; set; }
        public String Prefix { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int ModifiedBy { get; set; }
        public DateTime ModifiedDate { get; set; }

        //EXTRA 
        public String GroupName { get; set; }

    }
}
