//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSLERP.DataManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class s_Resource
    {
  
        public int R_ID { get; set; }
        public string R_ResourceName { get; set; }
        public string R_DisplayName { get; set; }
        public string R_M_ID { get; set; }
        public bool R_Status { get; set; }
        public string R_Tag { get; set; }
        public string R_SM_ID { get; set; }
        public string R_Url { get; set; }

        public string Parent_R_ID { get; set; }
        public bool Is_Menu { get; set; }

        public int R_Order { get; set; }

        public int Menu_Order { get; set; }

        public string icon { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    }
}
